rocola/rocola/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

rocola/web/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('getalbums/', views.getalbums, name='getalbums'),
    path('detalle/', views.detalle, name='detalle'),
]

rocola/web/forms.py
from django import forms
from web.models import *

class MainForm(forms.Form):
    artista_selector = forms.ModelChoiceField(queryset=Artist.objects.all().order_by('name'), to_field_name='artist_id',label="Artista", widget=forms.Select(attrs={'class':'form-select'}), required=False, empty_label="Todos")
    album_selector = forms.ModelChoiceField(queryset=Album.objects.all().order_by('title'), to_field_name='album_id',label="Album", widget=forms.Select(attrs={'class':'form-select'}), required=False, empty_label="Todos")
    
    
    

rocola/web/templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django_Rocola</title>

    <meta name="description" content="Sistema de gestión de rocolas" />
    <meta name="keywords" content="rocolas, música, gestión" />
    <link rel="stylesheet" href="assets/css/main.css">

    <!-- Se integra Fontawesome -->
    <script src="https://kit.fontawesome.com/f6f28e61f7.js" crossorigin="anonymous"></script>
    <!-- Se integra Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
  </head>

  <body>
    
    <main>
      <div class="mt-4 container">
        {% block content %} 
        {% endblock %}
      </div>
    </main>
        {% comment %} <div class="section_objectFit">

        <div class="container">
            <div class="row">
                <div class="col">
                    <img src="" alt="Imágen 01" class="img-fluid">
                </div>
                <div class="col">
                    <img src="assets/img/02-desktop-wallpaper-tecnology-input-devices.jpeg" alt="Imágen 02" class="img-fluid">
                </div>
                <div class="col">
                    <img src="assets/img/03-desktop-wallpaper-tecnology-input-devices.jpeg" alt="Imágen 03" class="img-fluid">
                </div>
            </div>
        </div>
        
    </div>
    <footer>
      <p>Sitio Desarrollado en HTML5</p>
    </footer> {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>

</html>

rocola/web/templates/detalle.html
{% extends 'base.html' %} 
{% block content %}
<h1>Detalles    </h1>

<table class="table">
  <tbody>
    <tr>
      <th scope="row">Nombre del tema:</th>
      <td>{{ datos.cancion }}</td>
    </tr>
    <tr>
        <th scope="row">Compositor:</th>
        <td>{{ datos.compositor }}</td>
      </tr>
    <tr>
      <th scope="row">Nombre del Album:</th>
      <td>{{ datos.album }}</td>
    </tr>
    <tr>
      <th scope="row">Artista:</th>
      <td>{{ datos.artista }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

rocola/web/templates/form.html
{% extends 'base.html' %} 
{% block content %}
  <form action="" method="POST" class="py-3 px-4 d-flex">
    {% csrf_token %} 
    {% for field in form %}
    <div class="div-field px-2">
      <label class="form-label my-0">{{ field.label }}</label>
      {{ field }}
      {% if field.errors %}
        <div class="alert alert-danger mt-1" role="alert">
          {% for error in field.errors %}
            {{ error }}<br>
          {% endfor %}
        </div>
      {% endif %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
    {% endfor %}

    <button class="btn btn-primary px-2" style="width: 400px" type="submit">
      Filtrar
    </button>
  </form>

  {% include 'tabla.html' %} 


  {% block javascript %}
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script>
      $("#id_artista_selector").change(function () {
          const artistid = $(this).val();  // cambiar por el nombre del id deseado
          console.log(artistid);
          $.ajax({                       //
              type: "POST",
              url: '{% url "getalbums" %}',
              data: {
                  'artist_id': artistid,       // Coloque el id a consultar
                  'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
              },
              success: function (data) {   // `data` tiene la respuesta a la consulta
                  let html_data = '<option value="">---------</option>';
                  data.forEach(function (data) {
                      html_data += `<option value="${data.album_id}">${data.title}</option>`
                  });
                  $("#id_album_selector").html(html_data); // replace the contents of the topic input with the data that came from the server
              }
          });
      });
  </script>
  {% endblock javascript %}

{% endblock %}

rocola/web/templates/tabla.html
{% extends 'base.html' %} 
{% block content %}

<div class="tabla-datos mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">TrackId</th>
        <th scope="col">Nombre</th>
        <th scope="col">Duración [ms]</th>
        <th scope="col">Acción</th>
      </tr>
    </thead>
    <tbody>
      {% for item in tracks %}
      <tr>
        <th scope="row">{{item.track_id}}</th>
        <td>{{item.name}}</td>
        <td>{{item.milliseconds}}</td>
        <td>
            <form action="detalle/" method="POST">
              {% csrf_token %}
              <button class="btn btn-primary" type="submit" value="{{ item.track_id}}" name="detalle_id">Ver</button>
            </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}